require("options")
require("plugins")
require("keymaps")

require("gruvbox_cfg")
require("autopairs_cfg")
require("treesitter_cfg")
require("lualine_cfg")
require("gitsigns_cfg")
require("telescope_cfg")
require("impatient_cfg")
require("mason_cfg")
require("mason_lspconfig_cfg")
require("lspconfig_cfg")
require("mason_null_cfg")
require("null_cfg")
require("cmp_cfg")
